### ISSUE TITLE
Are segmentations preserved in JSON format?

### ISSUE THREAD

**Issue by rohitrango** [giddyyupp/coco-minitrain#10]
Hi,

Thank you for the paper and dataset, it is really useful for running ablations faster. 
I wanted to ask if the segmentations provided in the JSON files are changed in any way from the original`train2017` JSON.

Also, do you have any metrics for segmentation? 

Thanks a lot.

**Comment by giddyyupp** [comment]
Hello,

actually we skipped segmentation annotations during sampling, hence we havent measure anything. But they should be similar to the box annotations except for the images with `crowd` flag set where multiple person boxes have a single segmentation annotation. 
 
We will provide an updated version which also saves segmentation annotations.

thanks for using :)
