### ISSUE TITLE
How to use sample_coco.py

### ISSUE THREAD

**Issue by Keeping7** [giddyyupp/coco-minitrain#11]
Hi, thanks for your contribution. 
When i run sample_coco.py, the following lines appear:

loading annotations into memory...
Done (t=14.37s)
creating index...
index created!

Then it's stuck here all the time without generating the final json file. 

Could you help me? @giddyyupp @nerminsamet

**Comment by giddyyupp** [comment]
Hello,
In order to check debug outputs, could you run again with adding `--debug` flag and share the output with us.
Thanks

**Comment by Keeping7** [comment]
> Hello, In order to check debug outputs, could you run again with adding `--debug` flag and share the output with us. Thanks

When considering --debug, the issue is solved. Besides, I would like to ask: 

1. What is the relationship between the run_count and image_count? Does reducing the run_count have any effect on the final json file? 
2. How are the pictures in figures generated and analyzed? Is there any extra code?

Looking forward to your reply. 
Thanks

**Comment by giddyyupp** [comment]
1. actually there is no relationship. increasing run_count increases the chance of sampling much closer distribution to original coco dataset. image_count specifies how many images you want to sample from coco dataset. In mini-coco, we sampled 25k images. You could adjust this number based on your needs.
2. Figures are prepared by just reading mini-coco and original coco train json files. We left a commented visualization code in the sample_coco.py file.
