### ISSUE TITLE
Where can I find your json and images file?

### ISSUE THREAD

**Issue by jacob-kang** [giddyyupp/coco-minitrain#14]
I want to benchmark my model via coco-minitrain. As you know, training whole coco data is too slow to develop models.
So I decided to use coco-minitrain.

And you submitted your paper to ECCV with this coco-minitrain as a minor contribution.
But I downloaded your json file and downloaded via coco_download.py.

But this does NOT match at all.

Is there something I did wrong???????
I think not.
Simply to say, Could you share your json and image files when you used for making the benchmark table?

**Comment by giddyyupp** [comment]
Hi,
What does not match in the json or images, could you be more specific? 

I guess you already followed the correct steps but I am writing just in case:

Link to the Json file is in the [Readme](https://github.com/giddyyupp/coco-minitrain#download). 
For images, there is a downloader available in the [src folder](https://github.com/giddyyupp/coco-minitrain/blob/master/src/coco_download.py).

**Comment by jacob-kang** [comment]
Ok. To be more specific,

I got a json file from yout download. and then with instances_minitrain2017.json file, I used coco_download.py
As you know, coco_dowload.py needs a json file to download coco-minitrain.

And I downloaded the images file. The images are downloaded well without any problem.
But after that, I used mmdetection with the files and json,

There was a trouble.
The error was 'Not file found error'
There is not image 000000449108.jpg. So, I explore it, But nowhere.
Not only for that single image, but lots of other images were missed.

So, I downloaded COCO (not mini) and just match only json file.

But, I want to use a small storage space.
Could you figure out why these problems occurred?

**Comment by giddyyupp** [comment]
Hi,
I made a commit and updated the full url generation (which was problematic under windows). Could you try to download and check whether it works?

**Comment by jacob-kang** [comment]
I just ran the code and when I downloaded files,
This error 'The download exception is <urlopen error [Errno -2] Name or service not known' is occured.

**Comment by jacob-kang** [comment]
![image](https://user-images.githubusercontent.com/88817336/161930750-13054e92-67c1-49e4-a60e-4c7d808075ae.png)

**Comment by giddyyupp** [comment]
Now there is a link available to download images from Google Drive thanks to @bryanbocao.
