### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by bryanbocao** [giddyyupp/coco-minitrain#15]
```
Traceback (most recent call last):
  File "sample_coco.py", line 156, in <module>
    main()
  File "sample_coco.py", line 62, in main
    for i in keys[:parser.sample_image_count]:
TypeError: slice indices must be integers or None or have an __index__ method
```
when running ```sample_coco.py``` script.

**Comment by bryanbocao** [comment]
Just made a pull request. It simply casts input type from str to int.

**Comment by lichking23333** [comment]
I solved this problem by change 
for i in keys[:parser.sample_image_count]:
to
for i in keys[:int(parser.sample_image_count)]:

**Comment by bryanbocao** [comment]
> It simply casts input type from str to int.

Yes, as mentioned.

**Comment by TANKCHENG** [comment]
this debug could be pushed to project, thanks for your bug mentioned.

**Comment by giddyyupp** [comment]
Fix merged.

**Comment by TANKCHENG** [comment]
自动回复：             已收到，谢谢来信
