### ISSUE TITLE
read_data_sets 

### ISSUE THREAD

**Issue by nithya2503** [giddyyupp/coco-minitrain#22]
while running the sample_coco.py there's an error "cannot import name 'read_data_sets' from 'dataloader' "

**Comment by giddyyupp** [comment]
Hi,
in which line you get this error? could you share little bit detailed trace of the error.

**Comment by nithya2503** [comment]
Could you please tell me how to download the images from this MSCOCO mini dataset

**Comment by giddyyupp** [comment]
Now there is a link to download images in the ReadMe. Please check it.
