### ISSUE TITLE
Keypoints data in the dataset

### ISSUE THREAD

**Issue by madhavr08** [giddyyupp/coco-minitrain#23]
Hey!
Amazing dataset!
I was hoping to get a small data set for my pose detection model but I couldnt find keypoints in the annotations file. Are the keypoints not included in this dataset?

Thanks!

**Comment by giddyyupp** [comment]
Hello,
Glad to hear you liked the dataset!

Now the subset for keypoint detection task is available. We look forward to your feedback!
