### ISSUE TITLE
DOUBT : What is the format of label ? are BBOX in some kind of ratio 

### ISSUE THREAD

**Issue by abangwal** [giddyyupp/coco-minitrain#26]
Example 
`img_id : 000000007278` have label as `[0 ,0.391727 ,0.221691 ,0.190391 ,0.196867] ` as far as i can understand `0` stands for class 2nd and 3rd element represent `x_min` and `y_min` respectively and 4th and 5th are width and height 

#### **But i can't understand how to convert the BBOX ratio to original coordinates**

**Comment by giddyyupp** [comment]
Hi,
The format is the minitrain is exactly the same as coco dataset. Could you check the same img_id in the original coco dataset to see that the values are same?

**Comment by abangwal** [comment]
Hi
Thanks for your reply 
The issue was resolved later :)
