### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by amirmk89** [giddyyupp/coco-minitrain#28]
Hi folks,

Thank you for curating the useful subset. It seems that the google drive link on your github readme is broken, could you please look into it?

Thanks

**Comment by giddyyupp** [comment]
Hello,
Yes, the link seems broken, but we are not the ones who created this link. The link was created and merged by #16, so I guess @bryanbocao deleted the file. However, there is a downloader script to create the dataset.

**Comment by bryanbocao** [comment]
@amirmk89 @giddyyupp Sorry for not notifying you, guys. My department at school suddenly set some limits on Google Drive storage so I have to delete some large files. I will send another link quickly.

**Comment by bryanbocao** [comment]
@amirmk89 Please find the download link here [coco_minitrain_25k.zip](https://ln5.sync.com/dl/0324da1d0/rmi7abjx-2dj4ktii-d9jcwgc5-s7fwwrb7).
 @giddyyupp I made a pull request to update the download link: https://github.com/giddyyupp/coco-minitrain/pull/29.

Thanks!

**Comment by giddyyupp** [comment]
Thank you @bryanbocao, PR merged.
