### ISSUE TITLE
Download link for coco-minitrain

### ISSUE THREAD

**Issue by ajithvcoder** [giddyyupp/coco-minitrain#3]
Could you give the download link for minitrain images ?

**Comment by ajithvcoder** [comment]
@giddyyupp  could you give coco mini train images link

**Comment by giddyyupp** [comment]
Hi,
there is no link available for images directly. first you need to download coco train images (http://images.cocodataset.org/zips/train2017.zip) and then using the json file, you can create coco-minitrain dataset.
hope this helps.

**Comment by ajithvcoder** [comment]
Okay but its 20+ GB , it would be helpful if you shorten the images and give a drive link
