### ISSUE TITLE
CenterNet code requires person_keypoints_val2017.json

### ISSUE THREAD

**Issue by toastedbaguatte** [giddyyupp/coco-minitrain#35]
hello there! I am currently attempting to train COCO minitrain on the CenterNet-better algorithm. However, as shown in the image below, I am required to have the person_keypoints_val_2017.json AND person_keypoints_train_2017.json file. I am only able to find the person_keypoints_train2017.json file but not the val one. May I ask where would it be? Thank you! 

![image](https://github.com/giddyyupp/coco-minitrain/assets/155293525/bdaed143-c991-42bb-81da-17b1825bc436)

**Comment by giddyyupp** [comment]
hello, 
you can directly use val set of COCO dataset. We only subsampled the train set, val sets remain the same as COCO.
