### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by UygarUsta** [giddyyupp/coco-minitrain#36]
Thank you for your great work, after clicking the link I get  "8026 This link has been deleted by the owner" error.
 
Thanks

**Comment by giddyyupp** [comment]
Hi, 
the link that is failing as described in the readme file is maintained by @bryanbocao, so maybe we need to ask him about it.

**Comment by UygarUsta** [comment]
Hi again,this link might be an alternative I think:

https://www.kaggle.com/datasets/trungit/coco25k/data

**Comment by bryanbocao** [comment]
@giddyyupp @UygarUsta The previous link was moved. I think checking the dataset and will upload a new link shortly. Thanks!

**Comment by bryanbocao** [comment]
@giddyyupp @UygarUsta
Just realized that one copy was uploaded to huggingface 1+ years ago:
https://huggingface.co/datasets/bryanbocao/coco_minitrain/blob/main/coco_minitrain_25k.zip

**Comment by UygarUsta** [comment]
@bryanbocao Thank you so much !
