### ISSUE TITLE
Downloading images using coco_download.py

### ISSUE THREAD

**Issue by emredonmez98** [giddyyupp/coco-minitrain#7]
There is a "/" missing at the end of line 37 in the scripts coco_download.py. I could not initiate download without it.

**Comment by giddyyupp** [comment]
hmm that is strange, in line 40 os.path.join adds that '/' actually. are you using Windows, because it worked under Linux.

**Comment by emredonmez98** [comment]
Yes I am using Windows. That is probably the reason.
