### ISSUE TITLE
split 10% instead of 20%

### ISSUE THREAD

**Issue by hachreak** [giddyyupp/coco-minitrain#8]
Hi @giddyyupp ,
what should I modify to obtain a 10% dataset of COCO? :smile: 
Thanks a lot!

**Comment by giddyyupp** [comment]
Hello,
in the code/sample_coco.py MAX_IMG_COUNT = 25000 value defines how many images you want to sample. 
So a value of 12000 would yield almost 10%.

**Comment by hachreak** [comment]
Cool! Thanks. :+1: 
I'll try...
