### ISSUE TITLE
Missing coco_class_labels.csv

### ISSUE THREAD

**Issue by Alvin0629** [giddyyupp/coco-minitrain#9]
Hi, 

Thanks for the contribution. When running the csv_to_coco_json.py, the 'coco_class_labels.csv' is missing.

FileNotFoundError: [Errno 2] No such file or directory: 'coco_class_labels.csv''

Could pls add this file? Thanks!

**Comment by Oliviaaa99** [comment]
Hi, I also met the same problem and cannot get the sampled jason file. Could you upload it?
Thanks.

**Comment by Oliviaaa99** [comment]
Hi, I also met the same problem and cannot get the sampled Json file. Could you upload it?
Thanks.

**Comment by giddyyupp** [comment]
hello,
actually it is here: https://drive.google.com/file/d/1xmjxfdnFxZnD1IFpkpj2Yub9Wvv97-Kd/view
you just need to rename it to `coco_class_labels.csv` or you can set --csv_classes parameter as `class_labels.csv`

**Comment by ghost** [comment]
Get it. Thank you so much!

Samet Hi ***@***.***> 于2021年10月6日周三 上午1:54写道：

**Comment by Alvin0629** [comment]
> hello, actually it is here: https://drive.google.com/file/d/1xmjxfdnFxZnD1IFpkpj2Yub9Wvv97-Kd/view you just need to rename it to `coco_class_labels.csv` or you can set --csv_classes parameter as `class_labels.csv`

Successfully generate the sampled data, thanks for the help!
